version: "1.0"
type: route
data:
  url: "/storage/hpesmartarray/settings"
  title: _("Notification Settings")
  editing: true
  notificationTitle: _('Updated Smart Array Check settings.')
  component: omv-storage-hpesmartarray-settings-form-page
