#!/bin/bash
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    OpenMediaVault Plugin Developers
# @copyright Copyright (c) 2014-2022 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -euo pipefail

readonly HWRAID_BIN="/usr/sbin/ssacli"
[ ! -f "${HWRAID_BIN}" ] && exit 0

source /usr/share/openmediavault/sysinfo/functions

omv_sysinfo_begin_msg \
    "HPE Smart Array Information ($(LC_ALL=C
        "${HWRAID_BIN}" version |
         sed -n '/'''"$(\
                 basename "${HWRAID_BIN^^}" \
                 )"''' Version:/ s/^ *\(.*: \+.*\) \+.*/\1/p'))"

readonly DETECT_CONTROLLERS="$(LC_ALL=C
    "${HWRAID_BIN}" ctrl all show 2>&1 |
    sed '/^$/d' || true)"
[[ "${DETECT_CONTROLLERS}" =~ (No controllers detected)\. ]] && {
    omv_sysinfo_msg ""
    sed 's:^\s\+:   :g;s/^Error: //' <<< "${DETECT_CONTROLLERS}"
    omv_sysinfo_end_msg
    exit 0
}

_hwraid_msg() {
    omv_sysinfo_msg ""
    omv_sysinfo_msg "${1}: ${2%%$'\n'*}"
    omv_sysinfo_msg_separator
    # shellcheck disable=SC2001
    sed 's:^   ::' <<< "${2#*$'\n'}"
}

while read -r SLOTNR; do
    _hwraid_msg "CONTROLLER STATUS" "$(LC_ALL=C
        "${HWRAID_BIN}" ctrl slot="${SLOTNR}" show status |
        sed '/^$/d')"
    _hwraid_msg "CONTROLLER CONFIGURATION" "$(LC_ALL=C
        "${HWRAID_BIN}" ctrl slot="${SLOTNR}" show config |
        sed '/^$/d;
             s/\(^.*Slot [1-9]\+[0-9]*\).*/\1/;
             s/\(.*\)\(logical\)\(drive\)/\1\u\2 \u\3:/;
             s/\(.*\)\(physical\)\(drive\)/\1\u\2 \u\3:/')"
    _hwraid_msg "CONTROLLER DETAILS" "$(LC_ALL=C
        "${HWRAID_BIN}" ctrl slot="${SLOTNR}" show detail |
        sed '/^ *Slot:\|^$/d')"
    _hwraid_msg "PHYSICAL DRIVE DETAILS" "$(LC_ALL=C
        "${HWRAID_BIN}" ctrl slot="${SLOTNR}" pd all show detail |
        sed '/^ *\(Port\|Box\|Bay\).*\|^$/d;
             s/\(.*\)\(physical\)\(drive\)/\1\u\2 \u\3:/')"
done < <(sed -n 's/^.*Slot \([1-9]\+[0-9]*\).*/\1/p' <<< \
            "${DETECT_CONTROLLERS}")
omv_sysinfo_end_msg
exit 0
